### ISSUE TITLE
More stuff

### ISSUE THREAD

**Issue by dannguyen** [amandabee/scraping-for-journalists#2]
sorry don't know how to do a pull request:

```yaml

title: Doctors & Sex Abuse
publisher: Atlanta Journal-Constitution
url: http://doctors.ajc.com/about_this_investigation/
description: |
    At that point, our data journalism team wrote computer programs to “crawl” regulators’ websites – a process known as scraping – and obtain board orders. This required building about 50 such programs tailored to agencies across the country. That collected more than 100,000 disciplinary documents. 

title: Machine Bias
publisher: ProPublica
url: https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm
description: |
    Starting with the database of COMPAS scores, we built a profile of each person’s criminal history, both before and after they were scored. We collected public criminal records from the Broward County Clerk’s Office website through April 1, 2016. On average, defendants in our dataset were not incarcerated for 622.87 days (sd: 329.19).
```
